# Generated by Django 5.1.3 on 2024-11-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('hash_value', models.CharField(max_length=64)),
                ('algorithm', models.CharField(max_length=10)),
            ],
        ),
    ]
