# Generated by Django 5.1.3 on 2024-11-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('algorithm', models.CharField(default='shae256', max_length=10)),
                ('scan_frequency', models.CharField(default='daily', max_length=20)),
            ],
        ),
    ]
